services:
  gitea:
    image: docker.gitea.com/gitea:latest
    container_name: gitea

    networks:
      homenet:
        ipv4_address: 192.168.101.10

    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
    
    restart: unless-stopped

networks:
  homenet:
    external:
      name: homenet

volumes:
  gitea-data:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.60,nolock,soft,rw"
      device: ":/volume1/Services/gitea"
